# Generated by Django 4.2 on 2024-04-04 08:46

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_state_delete_company_country_status_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.fields.AutoField, to='api.country'),
        ),
    ]
